pct_files = ["pct.json"]
fct_files = ["fct.json"]
program_folders = ["_build/cobol/modules"]
map_folder = "_build/map"
job = "CARDDEMO"

[files]
data_path = "/home/engboris/aws-mainframe-modernization-carddemo/app/data/ASCII/"
handler = "vsam"

[good_morning]
prog = "COSGN00C"
tranid = "CC00"
