pct_files = ["pct.json"]
fct_files = []
program_folders = ["_build/cobol/modules"]
map_folder = "_build/map"
job = "CARDDEMO"

[files]
data_path = "app/data/EBCDIC/"
handler = "vsam"

[good_morning]
prog = "COSGN00C"
tranid = "CC00"
