# -*- Makefile -*-

BUILD_DIR ?= _build

# padbol / SuperKIX

PADBOL ?= padbol

# Assumes `padbol`'s binary file is actually in its source directory
SUPERKIX_LIB_DIR ?= \
	$(dir $(shell readlink -f \
		$(shell command -v $(PADBOL) 2>/dev/null)))superkix/target/debug

# GixSQL

GIXPP ?= gixpp

GIXPP_COPYBOOKS_DIR ?= /usr/local/share/gixsql/copy
GIX_LIB_DIR ?= /usr/local/lib

# GnuCOBOL

COBC ?= cobc

