# -*- Makefile -*-

BUILD_DIR ?= _build

# padbol / SuperKIX

PADBOL ?= superbol

# Assumes `padbol`'s binary file is actually in its source directory
SUPERKIX_LIB_DIR ?= /home/bas/superbol/lib
# GixSQL

GIXPP ?= gixpp

GIXPP_COPYBOOKS_DIR ?= /home/bas/superbol/share/gixsql/copy
GIX_LIB_DIR ?= /home/bas/superbol/lib

# GnuCOBOL

COBC ?= cobc

